if(NOT DEFINED ENV{WASI_SDK_PREFIX})
    message(FATAL_ERROR "WASI_SDK_PREFIX environment variable must point at a wasi-sdk install (e.g. /opt/wasi-sdk)")
endif()

set(WASI_SDK_PREFIX $ENV{WASI_SDK_PREFIX})

set(CMAKE_SYSTEM_NAME WASI)
set(CMAKE_SYSTEM_PROCESSOR wasm32)
set(CMAKE_SYSROOT "${WASI_SDK_PREFIX}/share/wasi-sysroot")

if(CMAKE_HOST_WIN32)
    set(WASI_SDK_EXE_SUFFIX ".exe")
else()
    set(WASI_SDK_EXE_SUFFIX "")
endif()
set(CMAKE_C_COMPILER "${WASI_SDK_PREFIX}/bin/clang${WASI_SDK_EXE_SUFFIX}")
set(CMAKE_CXX_COMPILER "${WASI_SDK_PREFIX}/bin/clang++${WASI_SDK_EXE_SUFFIX}")
set(CMAKE_C_COMPILER_TARGET wasm32-wasip1-threads)
set(CMAKE_CXX_COMPILER_TARGET wasm32-wasip1-threads)

set(CMAKE_EXECUTABLE_SUFFIX ".wasm")

set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)

set(CMAKE_C_FLAGS_INIT "-D_WASI_EMULATED_SIGNAL -D_WASI_EMULATED_PROCESS_CLOCKS -pthread")
set(CMAKE_CXX_FLAGS_INIT "-D_WASI_EMULATED_SIGNAL -D_WASI_EMULATED_PROCESS_CLOCKS -pthread -fno-exceptions")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-lwasi-emulated-signal -lwasi-emulated-process-clocks -pthread")
